var etsyObjects = {}

module.exports = {
    beforeEach: browser => {
        etsyObjects = browser.page.etsyObjects()
        etsyObjects.navigate()
    },
    after: browser => {
        browser.end()
    },
    'Login': browser => {
        etsyObjects
            .click('#sign-in')
            .waitForElementVisible('#join_neu_email_field')
            .setValue('#join_neu_email_field', 'dvmtntest@gmail.com')
            .setValue('#join_neu_password_field', 'test123')
            
            .click('.btn.btn-large.width-full.btn-primary')

    },
    'Remove Item From Cart': browser => {
        etsyObjects
            .setValue('#search-query','job stone ffxiv')
            .click('.btn.btn-primary')
            .waitForElementVisible('#dropdown-label')
            .click('[src="https://i.etsystatic.com/14466015/d/il/2af182/1468277942/il_340x270.1468277942_4hff.jpg?version=0"]')
            browser.windowHandles(function(result) {
                var handle =  result.value[1]
                browser.switchWindow(handle)
            })
            .waitForElementVisible('.wt-badge.wt-badge--status-03', 10000)
            .click('#inventory-variation-select-0')
            browser.keys([browser.Keys.ARROW_DOWN, browser.Keys.ARROW_DOWN, browser.Keys.ENTER])
            .pause(2000)
            .click('.btn-text')
        .useXpath()
            .click('(//*[@name="listing-quantity"])[2]')
            browser.keys([browser.Keys.NUMPAD5, browser.Keys.ENTER])
        .useCss()
        .pause(2000)
            .click('[rel="remove"]')
            .pause(2000)
            .verify.elementNotPresent('.listing-title.text-gray.break-word')
    },
    'Favorite': browser => {
        etsyObjects
        .click('#sign-in')
        .waitForElementVisible('#join_neu_email_field')
        .setValue('#join_neu_email_field', 'dvmtntest@gmail.com')
        .setValue('#join_neu_password_field', 'test123')
        .click('.btn.btn-large.width-full.btn-primary')
         .setValue('#search-query','job stone charm')
         .pause(2000)
            .click('.btn.btn-primary')
            .click('[src="https://i.etsystatic.com/17049596/c/1661/1319/139/139/il/772009/1912710635/il_340x270.1912710635_5ui5.jpg"]')
            browser.windowHandles(function(result) {
                var handle =  result.value[2]
                browser.switchWindow(handle)
            })
        .click('[data-source="listing-page-favorite-listing-button"]')
        .click('[aria-label="Your account"]')
        .pause(2000)
        .click('#profile-link-label')
        .waitForElementVisible('[class="text-gray text-truncate mb-xs-0 text-body"')
        .verify.elementPresent('[class="text-gray text-truncate mb-xs-0 text-body"')
    .useXpath()
        .click('(//div/button/div/span)[3]')
        .pause(2000)
        .refresh()
        .pause(2000)
        .verify.elementNotPresent('[src="https://i.etsystatic.com/17049596/c/1661/1319/139/139/il/772009/1912710635/il_340x270.1912710635_5ui5.jpg"]')
    },
    'Change Locale': browser => {
        etsyObjects
        .waitForElementVisible('(//*[contains(text(), "United States")])[2]')
    .useXpath()
        .click('(//*[contains(text(), "United States")])[2]')
    .useCss()
        .click('#locale-overlay-select-region_code')
        browser.keys([browser.Keys.ARROW_UP, browser.Keys.ARROW_UP, browser.Keys.ARROW_UP, browser.Keys.ARROW_UP, browser.Keys.ENTER])
        .click('#locale-overlay-select-language_code')
        browser.keys([browser.Keys.ARROW_DOWN, browser.Keys.ARROW_DOWN, browser.Keys.ARROW_DOWN, browser.Keys.ARROW_DOWN, browser.Keys.ENTER])
        .click('#locale-overlay-save')
        .pause(2000)
    .useXpath()
        .verify.containsText('//h1','ハンドメイド')
        .click('//*[contains(text(), "日本語")]')
        .pause(1000)
    .useCss()
        .click('#locale-overlay-select-language_code')
        browser.keys([browser.Keys.ARROW_DOWN, browser.Keys.ARROW_DOWN, browser.Keys.ARROW_DOWN, browser.Keys.ARROW_DOWN, browser.Keys.ENTER])
        .click('#locale-overlay-save')
        .pause(2000)
    .useXpath()
        .verify.containsText('//*[contains(text(), "Нужна")]', 'Нужна')
        .click('//*[contains(text(), "Русский")]')
    .useCss()
        .click('#locale-overlay-select-language_code')
        browser.keys([browser.Keys.ARROW_UP, browser.Keys.ARROW_UP, browser.Keys.ARROW_UP, browser.Keys.ARROW_UP, browser.Keys.ARROW_UP, browser.Keys.ARROW_UP, browser.Keys.ARROW_UP, browser.Keys.ARROW_UP, browser.Keys.ENTER])
        .click('#locale-overlay-select-region_code')
        browser.keys(['u', browser.Keys.ARROW_DOWN, browser.Keys.ENTER])
        .click('#locale-overlay-save')
        .pause(2000)
    .useXpath()
        .verify.containsText('//*[contains(text(), "Need help?")]', 'Need help?')
    .useCss()
    },


    //This test's has issues with not being able to interact with elements even though the selectors
    //are correct and visible on the page when it should be interacting with them 


    // 'Headers': browser => {
    //     etsyObjects
    //     .resizeWindow(400,800)
    //     .click(browse)
    // .useXpath()
    // .pause(1000)
    //     .click('(//li/div/div[@class="flag-body"])[1]')
    // .api.pause(2000)
    //     .click('(//li/div/div[@class="flag-body"])[7]')
    // .useCss()
    // .pause(1000)
    //     .click('[href="/c/accessories/hats-and-caps?ref=catnav-10855"]')
    //     .pause()
    // .useXpath()
    // .pause(1000)
    //     .verify.containsText('//h1', 'Hats & Caps')
    // .useCss()
    // .pause(1000)
    //     .click(browse)
    // .useXpath()
    // .pause(1000)
    //     .click('(//li/div/div[@class="flag-body"])[7]')
    // .useCss()
    //     .click('[href="/c/accessories/scarves-and-wraps?ref=catnav-10855"]')
    // .useXpath()
    // .pause(1000)
    //     .verify.containsText('//h1', 'Scarves & Wraps')
    // .useCss()
    // .pause(1000)
    //     .click(browse)
    // .useXpath()
    // .pause(1000)
    //     .click('(//li/div/div[@class="flag-body"])[7]')
    // .useCss()
    // .pause(1000)
    //     .click('[href="/c/accessories/keychains-and-lanyards?ref=catnav-10855"]')
    // .useXpath()    
    // .pause(1000)
    //     .verify.containsText('//h1', 'Keychains & Lanyards')
    // .useCss()
    // .pause(1000)
    //     .click(browse)
    // .useXpath()
    // .pause(1000)
    //     .click('(//li/div/div[@class="flag-body"])[2]')
    // .pause(1000)
    //     .click('(//li/div/div[@class="flag-body"])[14]')
    // .useCss()
    // .pause(1000)
    //     .click('[href="/c/clothing/womens-clothing?ref=catnav-10923"]')
    // .useXpath()
    // .pause(1000)
    //     .verify.containsText('//h1', "Women's Clothing")
    // .useCss()
    // .pause(1000)
    //     .click(browse)
    // .useXpath()
    // .pause(1000)
    //     .click('(//li/div/div[@class="flag-body"])[2]')
    //     .pause(1000)
    //     .click('(//li/div/div[@class="flag-body"])[16]')
    // .useCss()
    // .pause(1000)
    //     .click('[href="/c/clothing/boys-clothing?ref=catnav-10923"]')
    // .useXpath()
    // .pause(1000)
    //     .verify.containsText('//h1', "Boys' Clothing")
    // .useCss()
    // .pause(1000)
    //     .click(browse)
    // .useXpath()
    // .pause(1000)
    //     .click('(//li/div/div[@class="flag-body"])[3]')
    //     .pause(1000)
    //     .click('(//li/div/div[@class="flag-body"])[18]')
    // .useCss()
    // .pause(1000)
    //     .click('[href="/c/home-and-living/home-decor?ref=catnav-891"]')
    // .useXpath()
    // .pause(1000)
    //     .verify.containsText('//h1', 'Home Décor')
    // .useCss()
    // .pause(1000)
    //     .click(browse)
    // .useXpath()
    // .pause(1000)
    //     .click('(//li/div/div[@class="flag-body"])[3]')
    //     .pause(1000)
    //     .click('(//li/div/div[@class="flag-body"])[19]')
    // .useCss()
    // .pause(1000)
    //     .click('[href="/c/bath-and-beauty/bath-accessories?ref=catnav-891"]')
    // .useXpath()
    // .pause(1000)
    //     .verify.containsText('//h1', 'Bath Accessories')
    // .useCss()
    // .pause(1000)
    //     .click(browse)
    // .useXpath()
    // .pause(1000)
    //     .click('(//li/div/div[@class="flag-body"])[3]')
    //     .pause(1000)
    //     .click('(//li/div/div[@class="flag-body"])[20]')
    // .useCss()
    // .pause(1000)
    //     .click('[href="/c/pet-supplies/pet-clothing-accessories-and-shoes?ref=catnav-891"]')
    // .useXpath()
    // .pause(1000)
    //     .verify.containsText('[Pet Clothing, Accessories & Shoes]')
    // .useCss()
    // .pause(1000)
    //     .click(browse)
    // .useXpath()
    // .pause(1000)
    //     .click('(//li/div/div[@class="flag-body"])[4]')
    //     .pause(1000)
    //     .click('(//li/div/div[@class="flag-body"])[24]')
    // .useCss()
    // .pause(1000)
    //     .click('[href="/c/weddings/gifts-and-mementos/groomsmen-gifts?ref=catnav-10983"]')
    // .useXpath()
    // .pause(1000)
    //     .verify.containsText('//h1', 'Groomsmen Gifts')
    // .useCss()
    // .pause(1000)
    //     .click(browse)
    // .useXpath()
    // .pause(1000)
    //     .click('(//li/div/div[@class="flag-body"])[5]')
    //     .pause(1000)
    //     .click('(//li/div/div[@class="flag-body"])[30]')
    // .useCss()
    // .pause(1000)
    //     .click('[href="/c/books-movies-and-music/books/literature-and-fiction?ref=catnav-11049"]')
    // .useXpath()
    // .pause(1000)
    //     .verify.containsText('//h1', 'Literature & Fiction')
    // .useCss()
    // .pause(1000)
    //     .click(browse)
    // .useXpath()
    // .pause(1000)
    //     .click('(//li/div/div[@class="flag-body"])[6]')
    // .useCss()
    // .pause(1000)
    //     .click('[href="/c/art-and-collectibles/sculpture?ref=catnav-66"]')
    // .useXpath()
    // .pause(1000)
    //     .verify.containsText('//h1', 'Sculpture')
    // .useCss()
    // .pause(1000)
    //     .click(browse)
    // .useXpath()
    // .pause(1000)
    //     .click('(//li/div/div[@class="flag-body"])[7]')
    //     .pause(1000)
    //     .click('(//li/div/div[@class="flag-body"])[37]')
    // .useCss()
    // .pause(1000)
    //     .click('[href="/c/craft-supplies-and-tools/paper-party-and-kids/papercraft/card-making-and-stationery?ref=catnav-562"]')
    // .useXpath()
    // .pause(1000)
    //     .verify.containsText('//h1', 'Card Making & Stationery')
    // }
}